version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    # Hostname to use for container, required in some instances for the rest of the stack to each other endpoints
    hostname: gluetun
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8085:8085 # qbittorrent
      - 9117:9117 # Jackett
      - 8989:8989 # Sonarr
      - 9696:9696 # Prowlarr
      - 7878:7878 # radar
      - 8112:8112 # deluge
      - 58846:58846 #optional - deluge

    volumes:
      - /home/toddb/arr-stack/gluetun:/gluetun
      - /home/toddb/arr-stack/gluetun/wireguard/wg0.conf:/gluetun/wireguard/wg0.conf
    environment:
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
        # OpenVPN:
        #- OPENVPN_USER=
        #- OPENVPN_PASSWORD=
      # Wireguard:
      #- WIREGUARD_PRIVATE_KEY=yOO6Wju7oBz29NmlJTmQ/DghEBr/PwquYCz7/0guHGE= # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/nordvpn.md#obtain-your-wireguard-private-key
      #- WIREGUARD_ADDRESSES=10.13.114.77/24
      # Timezone for accurate log times
      - TZ=${TZ}
      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      - UPDATER_PERIOD=24h

  # qbittorrent:
  #   image: lscr.io/linuxserver/qbittorrent
  #   container_name: qbittorrent
  #   network_mode: "service:gluetun"
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=TZ=${TZ}
  #     - WEBUI_PORT=8085
  #   volumes:
  #     - /home/toddb/arr-stack/qbittorrent:/config
  #     - /mnt/DATA2/qbdownloads:/downloads
  #     - /mnt/DATA2/tv:/tv
  #     - /mnt/DATA2/movies/movies
  #   depends_on:
  #     - gluetun
  #   restart: always

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ${HOMEDIR}/arr-stack/deluge:/config
      - ${MNT_DATA}/delugedl:/downloads
      - ${MNT_DATA}/tv:/tv
      - ${MNT_DATA}/movies/movies
    depends_on:
      - gluetun
    restart: unless-stopped



  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - ${HOMEDIR}/arr-stack/jackett/data:/config
      - ${HOMEDIR}/arr-stack/jackett/blackhole:/downloads
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${HOMEDIR}/arr-stack/sonarr/data:/config
      - /mnt/DATA2/tv:/tv #optional
      - /mnt/DATA2/qbdownloads:/downloads #optional
      - ${MNT_DATA}/delugedl/:/delugedl
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - /home/ubuntu/docker/arr-stack/prowlarr/data:/config
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${HOMEDIR}/radarr/data:/config
      - /mnt/DATA2/movies:/movies #optional
      - /mnt/DATA2/qbdownloads:/downloads #optional
      - ${MNT_DATA}/delugedl/:/delugedl
    restart: unless-stopped