version: '3'
#---------------------------------------------------------------------#
#     Homarr - A simple, yet powerful dashboard for your server.      #
#---------------------------------------------------------------------#
services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - /home/toddb/homarr/configs:/app/data/configs
      - /home/toddb/homarr/icons:/app/public/icons
      - /home/toddb/homarr/data:/data
      - /home/todd:/home
    ports:
      - '7575:7575'
    networks:
      - frontend
    restart: unless-stopped

networks:
  frontend:
    external: true
