services:
  freeipa:
    image: freeipa/freeipa-server:rocky-9
    restart: unless-stopped
    hostname: freeipa.coho.local
    environment:
      IPA_SERVER_HOSTNAME: freeipa.coho.local
      TZ: "Asia/Tehran"
    tty: true
    stdin_open: true
    cap_add:
      - NET_ADMIN
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - freeipavol:/data
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.lo.disable_ipv6=0
    security_opt:
      - "seccomp:unconfined"
    command:
      - -U
      - --domain=coho.local
      - --realm=coho.local
      - --http-pin=VMware1!
      - --dirsrv-pin=VMware1!e
      - --ds-password=VMware1!
      - --admin-password=VMware1!
      - --no-host-dns
      - --unattended
    ports:
      - "81:80"
      - "446:443"
      - "389:389"
      - "636:636"
      - "88:88"
      - "464:464"
      - "88:88/udp"
      - "464:464/udp"
      - "123:123/udp"
      - "7389:7389"
      - "9443:9443"
      - "9444:9444"
      - "9445:9445"
volumes:
  freeipavol: