services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: 'host'
    volumes:
      - /home/toddb/jellyfin/config:/config
      - /home/toddb/jellyfin/cache:/cache
      - /mnt/DATA2/:/media
    restart: 'unless-stopped'